### ISSUE TITLE
Simplify baker2 private_network format.

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/Baker#27]
We want to go from
```yaml
  network:
    - private_network:
        ip: "192.168.31.33"
```

to
```yaml
ip: 192.168.31.33
```
