### ISSUE TITLE
Baker cluster support

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/Baker#45]
It has been a long-time coming for baker to support a cluster (multiple nodes). Here are some use cases and proposed formats:

- [ ] **Nomad cluster**

We have several projects making use of nomad. Nodes need docker, master node with consul.

```yaml
cluster:
  - nomad: 
      master:
        services:
          - consul
      nodes[3]:
        services:
          - docker
```

- [ ] **Spark cluster**

Spark is a pretty useful approach for doing analysis that might need very large amount of RAM.
```yaml
cluster:
  - spark: 
      nodes[10]:
        memory: 4GB
        cpu: 2
```

- [x] **Plain clusters**

For our git mining projects, it is useful to have multiple worker nodes to do a task.

```yaml
cluster:
  - plain: 
      nodes[10]:
        lang:
          - nodejs9
        services:
          - docker
```

- [ ] **Other**

It could be useful to have the ability to attach an ad-hoc node the cluster, especially, for things like logging, data collection, etc.

```yaml
     satellite:
        services:
          - log
```
