### ISSUE TITLE
R bakelet fails to install if *no packages* are provided.

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/Baker#69]
**Describe the bug**

R bakelet fails to install if *no packages* are provided.

The following error occurs.
```
VM is currently in state "running"
✔ Running apt-get update on VM
✔ Preparing python
✔ Installing python
✖ Preparing R
==> Error: TypeError: Cannot read property 'length' of undefined
```

**To Reproduce**

Given, the following baker.yml:

```yaml
name: Rplayground
vm:
   ip: 10.50.50.50
   memory: 2048
lang:
  - python2
  - R
```

**Expected behavior**
Be able to run without requiring packages.
Adding a packages object resolves error:

```
  - R:
      packages: coin
```
**Please complete the following information:**
MacOS
