### ISSUE TITLE
Issue installing R package

### ISSUE THREAD

**Issue by nischalshrestha** [ottomatica/Baker#72]
**Describe the bug**
R package could not be installed due to not being able to write to the default directory location: `/usr/local/lib/R/site-library`

**To Reproduce**
1. Use the baker.yml below...

```
name: Rplayground
vm:
   ip: 10.50.50.50
   memory: 2048
lang:
  - python2
  - R:
      packages: 
        - coin
        - ggplot2
```

2. Run `baker bake`
...

**Expected behavior**
Do `baker ssh` then run `R` and execute `library(ggplot2)` on the interpreter and it should be loaded with no error messages.

**Actual**
```
Error in library(ggplot2) : There is no package called 'ggplot2'
```

**Please complete the following information:**
 - OS: MacOS
 - Version 10.13.6 

**Additional context**
After running `baker ssh` I tried just running R with `sudo` and executed `install.packages("ggplot2")` which results in this message before successfully installing:

```
> install.packages("ggplot2")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
```
