### ISSUE TITLE
Implement Vault Feature

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/Baker#9]
Allow checkout of keys from a vault.

User adds this to baker.yml
```yml
bake:
  ansible:
    source: src/env/
    playbooks:
      - bootstrap.yml
      - configure.yml
  vault:
    source: src/env/vault.yml
    checkout: 
      key: alt-code-db-key
      dest: ~/.ssh/alt-code_rsa
```

User is prompted to enter password to checkout key from vault, which is copied to destination on VM.

![image](https://user-images.githubusercontent.com/742934/27239929-ec3ec858-52a0-11e7-9f2f-695679b9fcbd.png)

Now, key is copied to VM:
![image](https://user-images.githubusercontent.com/742934/27240050-5767848a-52a1-11e7-892a-ecccc2937e2b.png)
